### ISSUE TITLE
Transaction for large contract fails

### ISSUE THREAD

**Issue by Georgi87** [ethereum/cpp-ethereum#1467]
I tried to send a very big contract to the blockchain via AlethZero interface.

Bytecode: http://dumptext.com/LFFbSy0c

INFO Gas required: 2379539 total = 2370308 base, 9231 exec [0 refunded later]

I can execute the transaction. But after the transaction has been processed, getCode at the given address returns 0x0. However for smaller contracts everything works.

**Comment by ethers** [comment]
The open gas pricer issues might be related to this.

cpp team:
on develop 034e807, when I set AZ to 3000000 gas (@10szabo) and paste Georgi87's bytecode in AZ, this is what I see in the New Transaction dialog: 
```
ERROR Code deposit failed due to insufficient gas
INFO Gas required: 1554669 total = 1549068 base, 5601 exec [0 refunded later]
```

**Comment by gavofyork** [comment]
Indeed it does fail. And quite rightly.

Block gas limit is 3,141,592 GAS.

Basic transaction costs runs to 1,554,669 GAS (5,601 execution, the rest to pay for the humongous transaction).

Until now, you're only about half-way to the 3.1 MGAS limit, leaving a large 1.586 MGAS left for depositing your code.

However, you're then trying to deposit a program of 23.9 KB (!). This costs 23,900 bytes * 200 GAS/byte = 4.78 MGAS just for the deposit! Waaaaaaaay over!

Since 4.78 > 1.586 no code gets deposited.

**Comment by Georgi87** [comment]
Ok, understood. thanks for clearification.

So I got 1.586.923 GAS left for my code. The max code size can be 1586923/200 = 7934 Bytes?
