### ISSUE TITLE
Solc AST printer output (don't remove please...)

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#1508]
There's a worrying comment in solc:

```
// do we need AST output?
if (m_args.count(_argStr))
{
     ...
```

Maybe not, but it's very useful for some of us - the JSON format in particular. For example it allows me to do test coverage analysis in an emergent solidity contract [unit testing framework](https://www.youtube.com/watch?v=jEoVUajV3Uk). It has lots of info that the JSON interface does not have, and JSON makes it super easy to turn into js objects, and is a lot easier to analyze then source code.

AST, interface, opcodes, natspec, all of that's great for making tools. The solidity compiler in general is awsome - especially because of things like this. If nobody uses it I think it's only because people haven't really gotten that far yet, and it's just a matter of time before innovation starts.

**Comment by LefterisJP** [comment]
Hehe no worries man. If I am not imstaken I am the one who put it there. It's not a `TODO` or `TOTHINK`. It's more like a story of how the code reads. So if we need ast output we go into the `if`. Does not make much sense anymore since it's in its own function but originally I believe it was part of a much uglier ```if .. else if ... else``` and back there the comment was just added for clarity.

Just a note. What you refer to is the solidity command line interface which is just another interface to the Solidity compiler (which is basically a C++ library).
