### ISSUE TITLE
solc contract constructor json-abi

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1571]
Can we add contract constractor abi to solc output?

for this contract:

```solidity
contract hello {
    function hello() {
        Hello();
    }
}
```

abi looks like this:

```json
[]
```

but I would like it to be like this:

```json
[
   {
      "constant" : false,
      "inputs" : [],
      "name" : "hello",
      "outputs" : [],
      "type" : "constructor"
   }
]
```

**Comment by chriseth** [comment]
This is fixed now, though the output is a bit different:
```
[
  {
    "constant" : false,
    "inputs" : [],
    "type" : "constructor" 
  }
]
```
I.e. it neither has a "name" nor a "outputs" attribute. The reason is that the constructor is not called like a function, so the name is not needed to compute the signature hash and it might even be misleading since in other languages, the constructor might be called differently (note that the ABI is not only for solidity).
