### ISSUE TITLE
Mix's JS API does not seem to acknowledge account balance changes.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1658]
Trying to send a transaction through JS API of more ether than the sending account has fails, but after successfully sending ether web3.eth.getBalance() does not return anything different.

**Comment by yann300** [comment]
It's because by default getBalance use the latest mined block and not the pending block.
Try:
 - Execute the transaction, mine a block and then call getBalance()
or
 - Execute the transaction, and call getBalance with the param value "pending" =>
web3.eth.getBalance("0x546....", "pending")
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetbalance

**Comment by Smithgift** [comment]
It is. Apologies for the confusion.
