### ISSUE TITLE
Solidity does not like public arrays of structs that contain structs.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1788]
For a specific example:
```
contract StructsInsideStruct {
	struct a
	{
		bool some_flag;
	}
	struct b
	{
		a thing;
	}
	b[] public c;
}
```
will complain:
`Comp	error	10:09:26	L10,C2 Contract Error: Internal type is not allowed for public state variables.`

A non-public array is perfectly OK. Does this have to do with structs as return types? It might not be fixable now.

**Comment by chriseth** [comment]
The ABI does not support structs. As a workaround, we translate struct types whose non-mapping members are all ABI types in accessors (and only there for now) to a list of ABI types. Since `struct a` is not an ABI type, the conversion ends there. Of course, one might flatten the nested struct, but I would say this makes it even harder for the user to predict the signature of the accessor function.

**Comment by 4ntoine** [comment]
Sorry for returning back to this old issue. So are structs still not allowed to be public function arguments?
