### ISSUE TITLE
Eth doens't connect to anything unless using the -b -x flags

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1866]
buntu 14.04 , loaded the chain with AZ, then closed AZ and started eth. 
Nothing happens, seems happy re: upnp

Killed eth, started eth again using -b -x 50, within seconds started finding peers and continue downloading the chain. 

Sorry i can't give more info than that.

**Comment by subtly** [comment]
AZ and Eth don't use the same file to save the network.

This is also by design -- eth doesn't have an option to turn networking on or off and by default, it won't connect to anything.

@stephantual
Can you consolidate UI enhancements like this into one issue?

Right now, for AZ, we use Qt to save configs (network, beneficiary address, client name) and for eth it's file-based. Qt actually saves all of this in a plist file on MacOS and on Linux I think it depends on the WM. I've a few ideas of what we can do here and bring them up in the next standup call.

**Comment by stephantual** [comment]
Thanks Subtly, didn't realize it was a GUI issue.

I'm a bit confused when you say they don't use the same file to save the network - because on buntu I can clearly climb the chain with AZ up to a block, close it and load Eth, and it will pick up from that block.
