### ISSUE TITLE
ethminer windows dag creation fails

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#1943]
When creating dag with ethminer on windows, creation of the DAG fails. And, I don't think it creates the DAG. Log says it's loading from ethash, then done, but it only takes a few seconds and no file is saved. It's not generated the dag because that should take much much longer. ping @LefterisJP

**Comment by subtly** [comment]
And here is the most likely culprit:

![filepath](http://i.imgur.com/oltlFzV.png)

**Comment by LefterisJP** [comment]
Windows I/O ... will need to provide a fix and test it to see if it's indeed that.

**Comment by Genoil** [comment]
See #1914

**Comment by tcoulter** [comment]
@LefterisJP I should buy you a :beer:

As per the comments in [the stackoverlow article @LefterisJP linked to](http://stackoverflow.com/questions/9542611/how-to-get-the-current-users-home-directory-in-windows), people suggested using the function `SHGetFolderPath` instead of `SHGetFolderPathW`. When I compiled with `SHGetFolderPath`, ethminer was able to create my DAG successfully (giving percent output, even) and I was able to start mining. 

Note that Ethash's default directly is `AppData/Ethash`, which doesn't seem to be within the typical Windows conventions. As far as I can tell, `AppData/Roaming/Ethash` or `AppData/Local/Ethash` should be used (but I don't know which one). 

Still, `SHGetFolderPath` (and not `SHGetFolderPathW`) seems to be the way to go. My output when benchmarking is now this, instead of a crash: :tada: 

```
$ ethminer.exe -G -M --opencl-device 1
  D  12:15:29|main  #00004000ΓÇª
Benchmarking on platform: { "platform": "AMD Accelerated Parallel Processing", "device": "Tahiti", "version": "OpenCL 1.2 AMD-APP (1642.5)" }
Preparing DAG...
  i  12:15:44|main  Loading from libethash...
DAG  12:15:58|main  Generating DAG file. Progress: 0 %
DAG  12:16:10|main  Generating DAG file. Progress: 1 %
<snip>
DAG  12:34:52|main  Generating DAG file. Progress: 98 %
DAG  12:35:04|main  Generating DAG file. Progress: 99 %
DAG  12:35:15|main  Generating DAG file. Progress: 100 %
  i  12:35:15|main  Done loading.
  D  12:35:15|main  pause took 0
  i  12:35:15|gpuminer0  workLoop 0 #00000000ΓÇª #00000000ΓÇª
  UDs i n1g2 :pl3a5t:f1o5r|mma:i AnM D  kAiccckeOlfefra ttoeodk  P0a.r0al0l2el Processing

Warming up...
Using device: Tahiti(OpenCL 1.2 AMD-APP (1642.5))
Trial 1... 21575997
Trial 2... 21481487
Trial 3... 21481487
Trial 4... 21568810
Trial 5... 21488645
min/mean/max: 21481487/21519285/21575997 H/s
inner mean: 21510594 H/s
Phoning home to find world ranking...
Error phoning home. ET is sad.
```

**Comment by tcoulter** [comment]
This looks fixed. I'd recommend closing.

**Comment by subtly** [comment]
#1965
