### ISSUE TITLE
CUDA mining performance went down 20%

### ISSUE THREAD

**Issue by Benoit9** [ethereum/cpp-ethereum#2221]
It used to be about 13MH/s on a GTX780. It is now 10.5MH/s.

**Comment by subtly** [comment]
Can you try with --force-single-chunk?

**Comment by Benoit9** [comment]
Yes, back to 13MH/s with  --force-single-chunk
Is it a temporary fix? Will it be a default?

**Comment by LefterisJP** [comment]
I have a similar GPU as you do. All GPUs have a max allocateable memory limit that they report to OpenCL. We switched to allocating the DAG in chunks if the current DAG size does not fit in a single allocation. This is the safest way to go to guarantee less segfaults for our users.

Some times, like in your and my case, even if OpenCL reports a small allocateable memory value it can actually allocate more, which is why you can force a single chunk without a segfault. At some point you will be forced to remove the --force-single-chunk argument because you will get a sefault (due to the DAG having grown so much in size that you indeed need chunks).

For now this will be the default. I will see if there is a better way, and if there is, we will provide an update.

**Comment by LefterisJP** [comment]
Btw you can follow updates closely if you join the Skype mining channel. Any changes are announced there.

**Comment by Benoit9** [comment]
Thank you for the info, but there are way too many channels to keep track
of. The dev blog or github should be enough.

**Comment by LefterisJP** [comment]
Details like this you won't find the any blog. If you follow the github PRs though you will definitely spot all changes :)

**Comment by Benoit9** [comment]
The PR are one-liners at best.
Are there releases or tags that signals which versions are (kinda) stable?

**Comment by LefterisJP** [comment]
yes but very rarely, a version will get a tag. When we release this will change. Keep in mind we have not released yet. 

But our PRs are not all one liners. Take for example the one that added the aforementioned argument: https://github.com/ethereum/cpp-ethereum/pull/2169
