### ISSUE TITLE
The example 'contract.html' doesn't work?

### ISSUE THREAD

**Issue by yuzhangiot** [ethereum/cpp-ethereum#2240]
var watch = web3.eth.filter('latest');
 watch.watch(function (err, hash) {
var block = web3.eth.getBlock(hash, true);       //The problem is here!
......
}

It is because the value of  'hash' is undefined. What is the problem here?

**Comment by step21** [comment]
Are you sure you are connected to your node properly, do any other calls give results?
In the snippet you gave, the problem is actually probably in the watch.watch before, as it seems like hash is not defined, which is done by the watch function/filter. This might mean your web3 is not properly connected, did you check this?
