### ISSUE TITLE
enable bidirectional mining

### ISSUE THREAD

**Issue by samlavery** [ethereum/cpp-ethereum#2325]
Please add an option to send solved blocks to a different node than the one mining off of.  It will help miners optimize their setups and waste less energy. 

Right now, the act of propagating a solved block causes the node to fall behind and requires a variable amount of time to catch back up.  During this interval, miners are wasting their clockcycles.

**Comment by gavofyork** [comment]
would require a change in the API since the other node wouldn't otherwise know which workpackage was being solved. a good idea anyway, since it would allow nodes to know what block the solution is for rather than guessing that it's the last which was answered and hoping async behaviour doesn't invalidate the assumption.
