### ISSUE TITLE
GPUMiner: set workgroup size to 64/128/192/256

### ISSUE THREAD

**Issue by Genoil** [ethereum/cpp-ethereum#2328]
From an algo point of view it has to be a multiple of 8, but from a GPU point of view, a multiple of 64 (up until 256) gives much better performance. 

See http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/#50401334_pgfId-452494

```
The fundamental unit of work on AMD GPUs is called a wavefront. Each wavefront consists of 64 work-items; thus, the optimal local work size is an integer multiple of 64 (specifically 64, 128, 192, or 256) work-items per work-group.
``` 

Current setting is 32. Defaulting to 64 (already the search method default) gives quite a speed bump.

**Comment by programmerTim** [comment]
It should be 32 for nvidia cards and 64 for AMD, but no more. It was 64 when I wrote it.

**Comment by Genoil** [comment]
Actually, on NVidia, 64 gives better thread occupancy because with 32, it's limited by max warps per SMX (instead of limited by max VGPRs). With my CUDA port of your kernel, I actually use 128 for workgroup size to get best hashrate.

**Comment by LefterisJP** [comment]
The local workgroup size is still defaulting to 64.
https://github.com/ethereum/cpp-ethereum/blob/develop/libethash-cl/ethash_cl_miner.h#L56

**Comment by Genoil** [comment]
yes but it is called with 32:
https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/Ethash.cpp#L376

**Comment by LefterisJP** [comment]
Hmmm you are right. This change eluded me. I did not enter that argument there. Will investigate and see how to handle this.

**Comment by programmerTim** [comment]
Ok fair enough, I've not gone near a profiler on nvidia hardware (until
recently buying a laptop I didn't have access to a suitable GPU) and was
making a few assumptions based on working with GCN:

1. GCN was very VGPR limited, I managed to get 3 out of a maximum of 10
threads to fit by isolating bits of code in dummy branches. Since the
algorithm is memory heavy any improvements here would help a lot, but
unfortunately although I think VGPR use could be substantially lower, the
AMD compiler likes to go crazy and use as many as possible.

2. When the workgroup size is under or equal to 64, the compiler can remove
the barrier instructions for synchronisation between threads in a
workgroup. This is because the 64 work-items run in lock-step on the 16
wide SIMD over 4 cycles. Exceeding 64 gets rid of this optimisation and
performance suffers. I'd assumed something similar for nvidia.

3. Increasing workgroup size also increases LDS usage, for nvidia that eats
into the L1 cache.

Tim

**Comment by Genoil** [comment]
One of the reasons I went ahead porting your kernel to CUDA was because all the fancy NVidia profiling tools aren't supporting OpenCL kernels. 

1. On CUDA, the kernel is also VGPR limited. Unbounded, I'm at 98 registers, but using launch_bounds, I can get down to 72 or 64, resulting in 50/44% occupancy with similar performance. 

2. I've always understood that differently. I thought as long as the workgroup size is a multiple of 32 (on NVidia, 64 for AMD), cooperating threads will always run in lock step. As a result, my CUDA kernel only has a single sync instruction left (just before dag lookup). 

3. Yeah but it's only 8 bytes per work-item. Plenty left on most devices.

**Comment by programmerTim** [comment]
2. At least for GCN, only work-items in a single SIMD run in lockstep. Once
you go over the number of work-items that can fit in a single SIMD then you
need barrier instructions to keep them in sync.There's something about this
in one of pdfs from AMD IIRC. For GCN I don't see how there can be any
benefit exceeding a work group size of 64 since maximum SIMD occupancy has
already been achieved.

3. True.

OOI, what percentage of the theoretical memory bandwidth can you reach on
nvidia hardware?

**Comment by Genoil** [comment]
I measured the actual memory bandwidth on a GTX780using NSight Profiler. Got 136GB/s out of an advertised 288GB/s, that's 47%. This very close to the measured occupancy (49% out of a theoretical 50) with a 64 VGPR kernel. With 72 it's the same bandwidth but a lower occupancy (44%) but less register spilling.

In a few days I get 24 hours on a Tesla K80 cluster. Should be able to achieve 100% occupancy there.

**Comment by programmerTim** [comment]
Thanks, interesting that nvidia cards don't seem to get as close to their
theoretical bandwidth limits as AMD. It is good enough to meet the PoW
design requirements though.
