### ISSUE TITLE
Solidity: Fixed gas stipend when using send() + fallback function? address.send() vs address.call.value()();

### ISSUE THREAD

**Issue by simondlr** [ethereum/cpp-ethereum#2368]
Hi. I'm playing around with using send() and then triggering the fallback function to do extra code.

However, I ran into the issue that I was running out of gas on the fallback function. After debugging and finding this, https://github.com/ethereum/cpp-ethereum/issues/2069, it turns out send() does not pass gas along, and there is a fixed stipend (if I understand it correctly).

Thus, ultimately, it seems to me that when using send + fallback, the fallback code is inherently limited to how much it can execute?

A work around to achieve exactly the same is to do address.call.value(1)(); (which sends 1 wei and triggers the fallback & works).

Whether the address is a contract address or not, you can also send to it using the above method.

ie, normal_address.call.value(1)();
sends 1 wei to that address.

contract_address.call.value(1)();
sends 1 wei to the contract & triggers the FULL fallback function.

So send() is acting the same as address.call.value(wei)(); EXCEPT, doing a call() sends the gas along, allowing larger fallback functions to be executed.

Is this intended?

**Comment by chriseth** [comment]
Yes, this is intended. `send()` should not be used to execute a large amount of code on the receiving side. The reason is the following:
Imagine a crowdfunding contract where some malicious contract pledges. The funding fails and everyone is refunded (in a loop), also the malicious contract. The problem is that the malicious contract has an infinite loop in its fallback function. Now the implementer of the crowdfunding contract (or the compiler) has two options: Either she sends all the gas together with the refund or just a fixed amount. In the all-gas-case, it will never be possible to refund anyone because we will always run into out-of-gas. Concerning the fixed-gas-case: This is what has been chosen here, and you have to agree on some fixed amount. As we have the gas stipend anyway, we just sent no gas at all.

**Comment by simondlr** [comment]
Yes, that is a good example of how it can be abused. Good point. You want that fail-safe.

Just to confirm. So, the stipend will always be the same for the fallback function when using send() right? That can't be changed? It's hardcoded?

If so, just out of curiosity, how was this chosen? I might have a slight misunderstanding here. Is a stipend only created for this edge case?

**Comment by chriseth** [comment]
It is hardcoded in the EVM and applies to any call that includes a value transfer. I think the specific amount was chosen to allow for at least one log call.

**Comment by simondlr** [comment]
Okay, thanks @chriseth.

> It is hardcoded in the EVM and applies to any call that includes a value transfer.

So to just 100% confirm if I have this right. With any value transfer that happens, a gas stipend is added (even when gas is sent along, like with "address.call.value(wei)()")?

**Comment by chriseth** [comment]
Please don't pin me down on this, but yes: If you call a contract and supply a nonzero wei value, the called contract gets a certain amount of gas from the calling contract in addition to what the calling contract supplied manually. Of course, the gas is not produced out of thin air and has to be paid by the calling contract.

**Comment by simondlr** [comment]
Right, okay. Thanks for clarifying! Appreciate it. I'll close this now.

**Comment by nmushegian** [comment]
I think this should be made explicit in the wiki, I couldn't find this mentioned.
