### ISSUE TITLE
using openCL even if --cpu specified 

### ISSUE THREAD

**Issue by romanman** [ethereum/cpp-ethereum#2583]
in case cpu mining 
still looking for openCL

running: 
```
./eth --cpu --upnp off --peers 50 -r 111.0.0.1 --listen 10101 -t 2 --mining on
```

halts with:
```
[OPENCL]:No OpenCL platforms found
[OPENCL]:clEnqueueWriteBuffer(-36)
```

**Comment by LefterisJP** [comment]
I tried with latest develop and I can't reproduce. Which operating system is this? Ubuntu? Is this a build of the latest develop branch?

**Comment by romanman** [comment]
Yep it is ubuntu on standard DO server

**Comment by gavofyork** [comment]
is this with latest develop?

**Comment by romanman** [comment]
yes from today

**Comment by LefterisJP** [comment]
Hmmm I am sorry but I can not reproduce it. Running `./eth` with the arguments provided with latest develop does not seem to go to OpenCL code at all for me.

**Comment by romanman** [comment]
```
commit 18efffe220777a9fb9c587e5930c6cdf62d8d754
Author: Gav Wood <i@gavwood.com>
Date:   Sun Jul 26 00:36:14 2015 +0200

    Fix extraData reporting.
```

That is my commit...

**Comment by LefterisJP** [comment]
Roman I will try again to reproduce this later in a clean Ubuntu. Can you give me the exact cmake configuration you used to build?

**Comment by subtly** [comment]
@LefterisJP First time I ran this I hit the bug. However after that I pulled from develop and there wasn't a problem. However the first time it had to generate the DAG.

**Comment by LefterisJP** [comment]
Hmm I am trying with latest develop always, but now I made sure `.ethash` is empty. Still unable to reproduce. Will test later or tomorrow also on a clean Ubuntu VM that does not have any opencl library. But I don't think that can be the case since I put breakpoints in OpenCL code configuration and they never hit.

You said you reproduced this? Under which commit you were?

@Roman: Can you answer my above question? How did you compile?

**Comment by romanman** [comment]
Just compiled as minimal bundle, to workaround now I dissable it in cmake
