### ISSUE TITLE
eth crashing - out of range exception

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/cpp-ethereum#2646]
here is the trace:
https://gist.github.com/CJentzsch/1ca544b39971ddb6b811

**Comment by chriseth** [comment]
This is probably an exception leaving the destructor of `EthereumPeer` while another exception is already active.
We know from the logs that `m_asking` is `Hashes` and my guess would be that in the call of `abortSync` -> `EthereumHost::onPeerAborting` -> `PVXXSync::onPeerAborting`, the invariant check in PVXXSync fails and throws, probably because of a wrong `m_asking` value.

**Comment by gavofyork** [comment]
fixed in latest, i think. reopen if it comes again.
