### ISSUE TITLE
Add warning about external function calls with variably-sized return values

### ISSUE THREAD

**Issue by itsnotlupus** [ethereum/cpp-ethereum#2765]
Given this source file
```
contract One {
    function getString() returns (string hi) {
        return "Hi";
    }
}

contract Two {
    function doSomething(address ofone) {
        var hi = One(ofone).getString();
    }
}
```

`$ solc < contract`
```
<stdin>:9:9: Type error: Variable cannot have void type.
        var hi = One(ofone).getString();
        ^-----------------------------^
```

`$ solc --version`
```
solc, the solidity compiler commandline interface
Version: 0.1.1-0/Release-Linux/g++/int
```

(no difference when enabling optimizations.)

**Comment by chriseth** [comment]
Unfortunately, it is not possible to obtain the returned value of the function, because in the EVM, the caller has to reserve a fixed space in memory for the return value when doing the call. This basically makes dynamically sized return values unusable in contract-to-contract calls.
I will keep this issue open as an enhancement to improve the error message.

**Comment by itsnotlupus** [comment]
Ah, good to know. I guess I'll reflect those limitations in my contract interfaces.
Presumably, returning a bytes32 containing however many characters will fit is the best we can get here.

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository
https://github.com/ethereum/solidity/issues/13
