### ISSUE TITLE
ethminer cannot connect to geth anymore

### ISSUE THREAD

**Issue by pompomJuice** [ethereum/cpp-ethereum#2842]
```
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
```

**Comment by akstunt** [comment]
Can confirm. i can replicate this on all newer builds of ethminer using geth

**Comment by LefterisJP** [comment]
Yes geth can't properly connect to ehtminer at the moment. ethminer uses a [new JSON-RPC call](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submithashrate) which eth++ has implemented but geth has not. 

When geth implement it, this issue will be solved. In the meantme I will see if I can put something in ethminer to not fail at connection even if `eth_submitHashrate()` is not there.

**Comment by LefterisJP** [comment]
Yes geth can't properly connect to ehtminer at the moment. ethminer uses a [new JSON-RPC call](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submithashrate) which eth++ has implemented but geth does not accept the parameters in the same way.

This should work in both clients but works only in eth:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_submitHashrate","params":[14, "67"], "id":67}' --url http://localhost:8545 
```
geth returns

```
{"id":67,"jsonrpc":"2.0","error":{"code":-32602,"message":"could not decode, invalid type on field rate: not a string"}}
```

because it expects both fields to be string, while the hashrate is actually an int.


When geth implements it, the same way as the spec this issue will be solved. In the meantme I will see if I can put something in ethminer to not fail at connection even if an `eth_submitHashrate()` call fails

**Comment by akstunt** [comment]
Thanks!

**Comment by obscuren** [comment]
Everything in the RPC is hex strings. Go's accepting hex strings, c++ is sending decimals strings :-)

**Comment by dima9871** [comment]
Всем привет! Я не программист и для меня не понятно что,где и как писать Помогите пожалуйста!!! как запустить майнинг эфириума 
какую программу использовать и как ее запустить???
мой локал IP:192.168.178.23
напешите полный BAT или JONS файлы чтобы я просто скопировал и запустил майнинг. Заранее СПАСИБО!
