### ISSUE TITLE
Mining. - not sure if im doing it right.

### ISSUE THREAD

**Issue by Tihocan3** [ethereum/cpp-ethereum#2898]
System: Windows 7 64bits
I`m running .bat file with these commands:
geth --rpc --rpcaddr "localhost" --rpcport 8545

and I got this screen:
![min1](https://cloud.githubusercontent.com/assets/13917517/9424008/127e938e-48aa-11e5-93ee-bc982f982312.jpg)

Then I´m running another .bat file with these commands:
ethminer.exe -F http://eth1.nanopool.org:8888/0x92cb723386f13e903524e0b645c2e7f7e0376c70 -G

and I got this:
![min2](https://cloud.githubusercontent.com/assets/13917517/9424010/23833fe0-48aa-11e5-81d3-c19dcb3c9867.jpg)

Does anyone know what I´m doing wrong?

**Comment by jmiehau** [comment]
As far as I read, you don't need to run a Geth client because you are pointing a pool who gives you the work.

Regarding the mining with Nvidia, try to do a benchmark before. Being sure you have more than 1gb ram on it. 
https://www.reddit.com/r/ethereum/comments/368nic/advice_on_getting_ethminer_to_work_with_nvidia/

**Comment by LefterisJP** [comment]
You don't need to run a geth client since you are working with a pool as @jmiehau points out.

From the logs you are posting I am afraid that you can't GPU mine with your card.

You are getting:
```
Error GPU mining: clEnqueueMapBuffer(-4)
```

which means your card does not have enough memory to allocate the full DAG. And sure enough it seems that [GeForce GTX 650](https://www.techpowerup.com/gpudb/894/geforce-gtx-650.html) has only 1024 MB of memory.  Our algorithm needs at least 2GB of memory allocateable in a single chunk.

**Comment by Tihocan3** [comment]
Ty very much for the help guys :)
I´ll try to get a better GPU and then mining ETH.
