### ISSUE TITLE
eth --db-path writes data to OS default

### ISSUE THREAD

**Issue by onepix** [ethereum/cpp-ethereum#3000]
Same as https://github.com/ethereum/cpp-ethereum/issues/1183
I tried : 
`eth --db-path 'C:\'`
`eth --db-path "C:\"`
`eth --db-path C:\`

Ethereum directory still  appear each time into the default path

> C:\Users\X\AppData\Roaming

I would like to save Ethereum directory basically Ethereum Blockchain into the -db-path/-d but even if these parameters are recognised, nothing show up into the path I gave.

> eth version 0.9.41
eth network protocol version: 61
Client database version: 12041
Build: Windows/msvc/JIT/Release

From the official install

> bitsadmin /transfer cpp-ethereum "https://build.ethdev.com/builds/Windows%20C%2B%2B%20develop%20branch/Ethereum-win64-latest.exe" %temp%\eth++.exe & %temp%\eth++.exe

**Comment by bobsummerwill** [comment]
Hey @onepix!
Thanks for the report, but 0.9.41 is an ancient build, and will stop working on Mar 14th with the Homestead hardfork.     Please could you grab the latest build (https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.1) and if the issue is still present then log an issue against the webthree-umbrella repo?   This repository has been inactive for months.   Thank you!
