### ISSUE TITLE
which one is stable?

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3230]
hi

lot of branches and tags. which one is considered stable?

**Comment by bobsummerwill** [comment]
Everything happens on 'develop'.

We haven't had a release from this repo yet since returning development to `cpp-ethereum` from `webthree-umbrella`

The most recent release was v1.3.0 "Homecoming" ...

https://github.com/bobsummerwill/cpp-ethereum/releases/tag/v1.3.0

... though the tag is against the wrong branch.

Prior to that we had regular releases here:

https://github.com/ethereum/webthree-umbrella/releases

We will be back to doing that kind of normal release flow soon enough.
