### ISSUE TITLE
SIMD for miner?

### ISSUE THREAD

**Issue by acterhd** [ethereum/cpp-ethereum#3313]
Hello. WIll support SIMD (SSE4.2, AVX2) in ethereum miner?

**Comment by chfast** [comment]
The idea of computing 4 (or 8 with AVX-512) hashes in a single round is very interesting. But CPU will still lost to GPU because of the memory speed. 

However, we don't plan to do it. Mining is driven by the community for some time and we want it goes this way in the future.

You may want to ask here: https://github.com/Genoil/cpp-ethereum/issues.
