### ISSUE TITLE
../libethash/libethash.so: error: undefined reference to 'ceil'

### ISSUE THREAD

**Issue by 5chdn** [ethereum/cpp-ethereum#3316]
Latest build from develop branch fails with:

    [ 61%] Linking CXX executable ethvm
    ../libethash/libethash.so: error: undefined reference to 'ceil'
    collect2: error: ld returned 1 exit status
    make[2]: *** [ethvm/CMakeFiles/ethvm.dir/build.make:118: ethvm/ethvm] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1586: ethvm/CMakeFiles/ethvm.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 61%] Building CXX object test/libtestutils/CMakeFiles/testutils.dir/Common.cpp.o
    [ 62%] Linking CXX executable ethminer
    ../libethash/libethash.so: error: undefined reference to 'ceil'
    ../libethashseal/libethashseal.so: error: undefined reference to 'pthread_create'
    collect2: error: ld returned 1 exit status
    make[2]: *** [ethminer/CMakeFiles/ethminer.dir/build.make:122: ethminer/ethminer] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1488: ethminer/CMakeFiles/ethminer.dir/all] Error 2
    [ 62%] Building CXX object test/libtestutils/CMakeFiles/testutils.dir/StateLoader.cpp.o
    [ 62%] Building CXX object libwebthree/CMakeFiles/webthree.dir/Support.cpp.o
    [ 63%] Building CXX object libwebthree/CMakeFiles/webthree.dir/Swarm.cpp.o
    [ 64%] Linking CXX shared library libtestutils.so
    [ 64%] Built target testutils
    [ 64%] Building CXX object libwebthree/CMakeFiles/webthree.dir/libexecstream/exec-stream.cpp.o
    [ 65%] Linking CXX shared library libwebthree.so
    [ 65%] Built target webthree
    make: *** [Makefile:128: all] Error 2

GCC 6, Archlinux:

     $ gcc --version
    gcc (GCC) 6.2.1 20160830
    Copyright (C) 2016 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     $ uname -a
    Linux 4.7.4-1-ARCH #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016 x86_64 GNU/Linux

**Comment by bobsummerwill** [comment]
Hmm.   Interesting.

Both `ceil` and `pthread_create` are very low-level and this code hasn't changed in months.

Please could you try a clean build?   I wonder whether GCC got updated and you have some stale paths?

**Comment by 5chdn** [comment]
Unfortunately, this reproduces on a clean build.

**Comment by bobsummerwill** [comment]
OK - So it looks like it might be related to `-pthreads` versus `-lpthreads` semantics, presumably because threading leaks beyond just the link-step:

http://stackoverflow.com/questions/28029195/how-to-let-cmake-use-pthread-instead-of-lpthread

So it looks like we are linking the library, but maybe in the wrong way, and maybe Alpine Linux is now on a newer version of GCC and that subtle difference matters now where it didn't before?

Please could you try adding `-pthreads` in here?

https://github.com/ethereum/cpp-ethereum/blob/develop/cmake/EthCompilerSettings.cmake#L28

For the ceil one, that is `libm`, the math library, though again, why it has stopped working is a bit of a mystery.

Could you try adding this to the CMakeFile.txt for ethash?   We might need to play around a bit to get the right answer for this one.

TARGET_LINK_LIBRARIES(ethash m)

**Comment by bobsummerwill** [comment]
See also http://stackoverflow.com/questions/32816646/can-cmake-detect-if-i-need-to-link-to-libm-when-using-pow-in-c.

**Comment by 5chdn** [comment]
> Please could you try adding -pthreads in here?

Nope, issue persists.

**Comment by bobsummerwill** [comment]
That won't fix `ceil`, for sure, but it didn't fix `pthreads_create` either, @5chdn?

**Comment by 5chdn** [comment]
Sorry I was a bit rushed with that comment. Please, stay tuned.

**Comment by 5chdn** [comment]
Your proposed solutions are fixing this issue. Thanks. Here is how I did it:

    diff --git a/cmake/EthCompilerSettings.cmake b/cmake/EthCompilerSettings.cmake
    index d91c357..e94b97c 100644
    --- a/cmake/EthCompilerSettings.cmake
    +++ b/cmake/EthCompilerSettings.cmake
    @@ -25,7 +25,7 @@ endif(CCACHE_FOUND)
     if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") OR ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang"))
     
            # Use ISO C++11 standard language.
    -       set(CMAKE_CXX_FLAGS -std=c++11)
    +       set(CMAKE_CXX_FLAGS "-pthread -std=c++11")
     
            # Enables all the warnings about constructions that some users consider questionable,
            # and that are easy to avoid.  Also enable some extra warning flags that are not
    diff --git a/libethash/CMakeLists.txt b/libethash/CMakeLists.txt
    index afefa8b..442dad9 100644
    --- a/libethash/CMakeLists.txt
    +++ b/libethash/CMakeLists.txt
    @@ -37,4 +37,6 @@ if (CRYPTOPP_FOUND)
            TARGET_LINK_LIBRARIES(ethash ${CRYPTOPP_LIBRARIES})
     endif()
     
    +TARGET_LINK_LIBRARIES(ethash m)
    +
     install(TARGETS ethash RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)

**Comment by mrtizmo** [comment]
This same issue exists in Ubuntu 16.10. The patch listed by @5chdn resolved the issue for me.

**Comment by chfast** [comment]
This happens because ethash is a C library. pthread is always linked to C++ libs because C++ standard library requires it. That's not the case for C libs. With the m library might be similar.

But please link the libraries only to ethash and only for GCC. Also please use `-lpthread` as `-pthread` is not universal flag for all targets any more https://gcc.gnu.org/onlinedocs/gcc-6.2.0/gcc/Option-Summary.html#Option-Summary.

The merged #3340 breaks Windows.

**Comment by chriseth** [comment]
Can this be closed now?

**Comment by 5chdn** [comment]
yes
