### ISSUE TITLE
CI: Install cmake from https://cmake.org/download

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3331]
Ubuntu 14.04 does not provide recent CMake version. It is better to always install it from the CMake download page https://cmake.org/download.

**Comment by daniel-lucio** [comment]
stop asking this kind of things, this is the perfect way to make harder including cpp-ethereum into distributions.

if you dont have cmake3, install it yourself. Its quite easy.

**Comment by chfast** [comment]
What are taking about?

**Comment by pirapira** [comment]
@daniel-lucio I understand that this issue is only about the continuous integration servers that run on pull-requests.  This issue is not about what happens in end-users' machines.

**Comment by bobsummerwill** [comment]
@chfast Are you suggesting that we flip `install_deps.sh` to install CMake from their own website rather than using the versions in our own PPA?

**Comment by chfast** [comment]
Precise issue is: Trusty don't have cmake 3.5 available in any PPA. LLVM requires cmake 3.5. However, I've found out that cmake provides universal binaries that run on every x64 linux.

**Comment by bobsummerwill** [comment]
Right.   Well I would certainly have no objection to you updating the `install_deps.sh` so that it grabs those binaries rather than using the ones in our PPA.

Having us hosting binaries in our PPA which are inputs to our build process is something which I would like to get away from entirely - whether through building-from-source, or git sub-modules, or `install_deps.sh`.    We want the version control in our hands as much as possible, not to be dependent on random binaries per distro/version where we have no control over versions or build process.

**Comment by bobsummerwill** [comment]
The place we need to be sensitive is where we do things in that script which update the global environment.   We've hit that a couple of times already, with GCC installs, for example.

**Comment by chfast** [comment]
@daniel-lucio suggested we don't provide that for users, but only for CI.

**Comment by daniel-lucio** [comment]
The problem is that makign packages that download everything is the direct way to have a mess in a system. Not a big deal if you only manage your personal laptop, but when you manage more than one server, keeping track where things are its a challenge.

If the package needs cmake3, then in the CMakelist file, put that condition. Everyone will be responsible to download CMAKE using its prefered method (RPM, DEB or even compiling from the source)

**Comment by chfast** [comment]
Done in https://github.com/ethereum/cpp-ethereum/pull/3474.
