### ISSUE TITLE
BlockChainSync.cpp

### ISSUE THREAD

**Issue by wheatli** [ethereum/cpp-ethereum#3652]
I was confused by some codes, such as:
(1) BlockChainSync.cpp : 85  “removeItem” function which means to delete one item in m_headers/m_bodies， but it seems like removing a list in line 92/99

(2) what's the reason about setting m_state = SyncState::Blocks; (line 169) before continueSync . If continueSync send nothing, the state will not be recovery.

Anybody can help to explain for me ? thx very much!
someting more will be posted later...

**Comment by wheatli** [comment]
@chfast

**Comment by chfast** [comment]
Hi @wheatli, thanks for looking into this. I can't answer you right now, I'm not very familiar with this code. The BlockChainSync code is known to have some issues with its internal logic. Would you consider sending code changes as a PR?

cc @gumb0

**Comment by wheatli** [comment]
template<typename T> void removeItem(std::map<unsigned, std::vector<T>>& _container, unsigned _number)
{
	if (_container.empty())
		return;
	auto lower = _container.lower_bound(_number);
	if (lower != _container.end() && lower->first == _number)
	{
		auto new_list = std::move(lower->second);
		new_list.erase(new_list.begin());
		auto new_key = _number + 1;
		_container.erase(lower);
		if (new_list.size() > 0) {
			_container.insert(std::make_pair(new_key, new_list));
		}
		return;
	}
	if (lower ==  _container.begin()) {
		return;
	}
	--lower;
	if (lower->first <= _number && (lower->first + lower->second.size()) > _number) {
		auto new_list = std::move(lower->second);
		new_list.erase(new_list.begin(), new_list.begin() + (_number - lower->first + 1));
		auto new_key = _number + 1;
		lower->second.erase(lower->second.begin() + (_number - lower->first), lower->second.end());
		if (new_list.size() > 0) {
			_container.insert(std::make_pair(new_key, new_list));
		}
	}
}

**Comment by gumb0** [comment]
1. yeah, seems like removeItem deletes not only the requested header/block, but also the items following it with consecutive numbers. 
It's called only in one case - when we receive new block in onPeerNewBlock and at this moment we have some downloaded headers & blocks from previous sync. I'm not sure if this even happens

2. I'm not sure I understand the question here, but `m_state = SyncState::Blocks` in line 169 resumes the sync after it was paused because of BlockQueue being full.
