### ISSUE TITLE
True random - Quantum Random Number Generation 

### ISSUE THREAD

**Issue by tpmccallum** [ethereum/cpp-ethereum#4191]
It is possible that we could obtain unique and secure true random values from the Australian National University (ANU) Quantum Random Numbers Server < http://qrng.anu.edu.au/index.php > as apposed to using pseudorandomly generated values?
There is a C++ implementation at < https://github.com/pcragone/anurandom/tree/master/cpp11 > which I am very keen to try out (from an Ethereum integration standpoint; in a test environment). I am happy to code and test locally, however I would appreciate some guidance around the validity/necessity/practicability of such an integration with the decentralized architecture.

**Comment by chriseth** [comment]
Sorry, but using quantum random number generators is the core protocol is impossible because either different nodes will come up with different random numbers or you have to trust a single entity to produce random numbers, because the randomness itself cannot be verified.

If you want to suggest protocol updates, please use the EIP process ( https://github.com/ethereum/EIPs ), discuss on reddit or stackexchange.

This repository is only about a single implementation of Ethereum.

**Comment by tpmccallum** [comment]
Thank you @chriseth
