### ISSUE TITLE
Stratum protocol integration

### ISSUE THREAD

**Issue by educatedwarrior** [ethereum/cpp-ethereum#43]

**Comment by debris** [comment]
any update on this? Do we want to have stratum protocol before Frontier?

**Comment by kenshirothefist** [comment]
There is a heavily increasing interest in this matter. Two reasons:

1. The current getwork-like job work is heavy, with increasing hashing power it will become inefficient. Stratum is lightweight and it's absolutely needed for pools. The same was with Bitcoin, etc.

2. Many users would like to try mining, but don't own their own miners, therefore they would like to rent miners or rent hashing power based on Dagger-Hashimoto algorithm. However implementing renting based on current getwork-like is inefficient and requires lots of work for implementation in existing stratum based services (see https://forum.ethereum.org/discussion/3068/stratum-support-for-pooled-mining-support-decentralization#latest, https://bitcointalk.org/index.php?topic=428589.msg12526252#msg12526252, https://bitcointalk.org/index.php?topic=1173722.msg12467020#msg12467020, etc.)

Someone should take care of this and implement stratum as soon as possible, shouldn't be that hard at all.

**Comment by subtly** [comment]
@kenshirothefist We will get to this, although its quite possible the community will get there first. Services which broker miners aren't ideal and it would be better to see a stratum service where installing full nodes is necessary -- and I think this is reasonable once we have implemented optimizations with the state database. The intent is to move to stake-based system so if the community comes up with a solution then we'll keep focused on that.

**Comment by kenshirothefist** [comment]
@subtly Not sure what exactly do you mean by necessity of installing full nodes at miner brokers services? Miner broker services (such as NiceHash.com, MiningRigsRentals, BetaRigs, etc.) are about redirecting hashing power from providers (miners) to renter's pools (private or public) therefore there is no need for full node (even though running a full node is not a problem for any service, I guess).

I really think that you should get your hands on this rather than waiting for community. The big issue is that making full getwork-stratum proxy is a rather heavy job. A much much better solution is to have direct stratum protocol support in mining software as well as on pools. And since the current de-facto mining software is managed by cpp-ethereum (similar to cgminer in Bitcoin and other coins) it really makes sense to simply implement stratum protocol directly into cpp-ethereum. And also all the existing mining pools would then of course implement stratum protocol since it would significantly save them network bandwidth and compute resources.

And also, please, please make sure that you wont go on "reinventing the wheel" path ... simply implement the stratum protocol as it is, it will make much easier to integrate it since stratum protocol is well known among pool operators.

Thanks and keep up the good work! ;)

**Comment by nicehashdev** [comment]
What is actually needed is to make a method like bitcoin has - getblocktemplate. This method exposes much more data for block creation. Stratum actually relies on this extra data. Your current getwork method does not provide enough data so that stratum could be implemented on top of it.

Just make getblocktemplate and the community can take from here creating stratum support.

The benefits of getblocktemplate vs getwork are explained here: https://en.bitcoin.it/wiki/Getblocktemplate

Bitcoin started with getwork and by now this method is obsolete and replaced by getblocktemplate. For long term prosperity of your cryptocurrency, you should really consider this, and there are plenty of services waiting for getblocktemplate to be available so mining abilities of this cryptocurrency can be fully utilized in every possible way.

**Comment by chriseth** [comment]
Closing as currently out of scope.
