### ISSUE TITLE
--fillchain failure on a general state test that passes

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4396]
```
test/testeth -t StateTestsGeneral/stPreCompiledContracts -- --filltests --fillchain --singletest modexp_1_0_0_1000000
```
shows some failures like
```
/home/ubuntu/yoichi/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(478): error: in "StateTestsGeneral/stPreCompiledContracts": modexp_1_0_0_1000000_d0g0v0_Byzantium Check State: 3535353535353535353535353535353535353535: incorrect balance 3000000000000175743, expected 5000000000000175743
modexp_1_0_0_1000000_d0g0v0_Byzantium
```

However,
```
test/testeth -t StateTestsGeneral/stPreCompiledContracts -- --singletest modexp_1_0_0_1000000
```
shows no failures.

**Comment by winsvega** [comment]
this is because you changed mining reward. state tests has no mining reward so it's expect section contains no reward. but when converted into blockchain test such reward added manually. 
change is here. need to get reward like in calculate reward function in doBlockchain tests
https://github.com/ethereum/cpp-ethereum/blob/develop/test/tools/libtesteth/ImportTest.cpp#L144
