### ISSUE TITLE
Select Win64 architecture on Windows

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4503]
By default, on Windows CMake generates project for Visual Studio for Win32 architecture.
Tweak this to always use Win64 by setting `CMAKE_GENERATOR_PLATFORM`: https://cmake.org/cmake/help/v3.9/variable/CMAKE_GENERATOR_PLATFORM.html.

Also update README and simplify instructions for building on Windows.

**Comment by bahelit** [comment]
Would like to pick this up, will give me a reason to setup up the build environment on my laptop.

**Comment by chfast** [comment]
@bahelit it's yours. Do you have any practice with CMake?

**Comment by bahelit** [comment]
Just cloned the repo, and successfully built the project.

So we are wanting to detect if we are on Windows and set the correct compiler within CMake without passing the argument -G "compiler version"?

**Comment by chfast** [comment]
I don't know exactly what's possible, but ideally:

1. `cmake ..` should build with "Visual Studio 14 2015 Win64" (build with "Visual Studio 14 2015" now).
2. `cmake .. -G "Visual Studio 14 2015"` should be an error.
3. `cmake .. -G "MinGW Something"` should at least try to use MinGW.

In other words, for people that have "Visual Studio 2015" installed, they should be allowed to skip `-G` option. This https://cmake.org/cmake/help/v3.9/variable/CMAKE_GENERATOR_PLATFORM.html might be helpful, but I have investigated it a lot.

Try to inform us on progress. If it would take long time, might not be worth it.

**Comment by bahelit** [comment]
CMake will automatically detect the presence of the visual studio compiler, the only problem is that it defaults to creating the project as an x86 build. 

Successfully created and built the solution with Visual Studio 2017 community edition with the following commands:
`mkdir build && cd build`
`cmake .. -A x64`

It's not as simple as just having `cmake ..` but is better then having to specify the Visual Studio version, which is unnecessary as cmake automatically does this.

Have already modified the README.md with the new steps and a recommendation of Visual Studio 2017 instead of 2015.
