### ISSUE TITLE
Parallelize testeth --filltests

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4546]
* Is there any way to run test cases in parallel with boost_test?
* There should be an option `-jn` with which `runAllTestsInFolder()` launches n threads.

**Comment by winsvega** [comment]
if its possible to parse to ctest comand line arguments we could do this easily.
@chfast

**Comment by pirapira** [comment]
`ctest`?

**Comment by winsvega** [comment]
ctest

**Comment by yxliang01** [comment]
@winsvega Would you like to elaborate further? Parallelizing `--filltests` is much needed in my use case. Thanks a lot.

**Comment by winsvega** [comment]
filltest for General StateTests is parallel on retesteth. 
If you build testeth you could specify --filltests for ctest with DTestethFlags (check with cmake the name of this option)

**Comment by yxliang01** [comment]
@winsvega Are you suggesting that we can make `ctest` running multiple testeth processes at the same time to achieve parallelism? I understand that retesteth, however, it's still unstable as suggested in its readme.md...

**Comment by winsvega** [comment]
General State Tests on geth are stable

Yes. With ctest just run multiple testeth commands

**Comment by yxliang01** [comment]
@winsvega  Multiple independent testeteh is exactly what I'm doing but it is less ideal when the number of test cases is large - overhead becomes an issue.

To confirm, do you mean that retesteth running on geth for General State Test is stable? If so, I'll give it a try. I didn't try it because of the sentence `! notice: This is a prototype and WIP!` in retesteth README.md .

Thanks for your help

**Comment by winsvega** [comment]
Yes. That sentence is outdated. I use retesteth more than testeth now. And if smth an issue report with a pm message so I would fix it.
