### ISSUE TITLE
Support eth_chainId

### ISSUE THREAD

**Issue by axic** [ethereum/cpp-ethereum#4810]
See https://github.com/ethereum/EIPs/pull/695 and https://github.com/paritytech/parity/pull/6329 (merged into parity).

This would be useful for the upcoming ewasm testnet & tooling around it.

**Comment by halfalicious** [comment]
I can take this one...a couple of quick questions:

- Is there any documentation for regenerating `libweb3jsonrpc\Ethface.h` after I've added the new chainId function to `eth.json`? I've tried running `jsonrpcstub eth.json --cpp-server=dev::rpc::EthFace` but there are some differences between my generated file and the existing one (e.g. my `EthFace` class extends `jsonrpc::AbstractServer<EthFace>` rather than `ServerInterface<EthFace>`). Apologies if this is a naive question, I haven't used jsonrpcstub before. 
- Same goes for `tests\unittests\libweb3jsonrpc\WebThreeStubClient.h` - is there any documentation for how to regenerate this? Additionally, which json file do I need to update? I don't see one in `tests\unittests\libweb3jsonrpc`

Thank you!
