### ISSUE TITLE
Weird port being recorded: 0 on stable binaries on two platforms.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#790]
On Windows 7, using the latest stable binary (cpp-ethereum-vs2013-0.7.13-20141219130558-6be33f.7z) will not connect to the global testnet, saying "Weird port being recorded: 0". It will do this regardless of whether it is behind a NAT or directly connected to the Internet.

On Ubuntu 14.04, (__on an entirely different computer!__) using the latest stable from the PPA as specified, it will not connect to the global testnet, saying "Weird port being recorded: 0". It will do this regardless of whether it is behind a NAT (though in this case it insists that it punched through) or directly connected to the Internet.

At this point I'm stumped. Two computers, two operating systems, and any amount of messing with the network has gotten me zilch.

**Comment by gavofyork** [comment]
Oops - sorry our host provider had shut our service down without notice. That has been moved onto another server/provider now, so all should be working again now. Not you may have to press Go twice to make it happen - this is a known bug and will be fixed in PoC-8.

Weird port being recorded is nothing to worry about. That particular message's text is made slightly less worrying in the latest version.

Reopen if you're still having difficulties.
